name: CI

on:
    push:
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 6.0.101

            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x

            - run: npm ci

            - run: npm run build
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
